---
title: "Linux 系统升级内核版本"
weight: 80
---
== 背景

在使用 Linux 发行版的时候，很多人都会遇到各种各样的问题，比如：*网卡不能使用，亮度不能调节，触摸板不能识别，蓝牙不能使用，应用软件要求的内核版本不符等等*，这些都和 Linux 的内核有关系。

== 操作步骤

=== 1、查看当前内核版本

[source,shell]
----
uname -r
uname -a
cat /etc/redhat-release
----

=== 2、升级内核

. 更新yum源
+
[source,shell]
----
yum -y update
----

. 启用 ELRepo 仓库
+
ELRepo 仓库是基于社区的用于企业级 Linux 仓库，提供对 RedHat Enterprise（RHEL）和其他基于 RHEL 的 Linux 发行版（CentOS、Scientific、Fedora 等）的支持。

. ELRepo仓库的公共密钥

+
[source,shell]
----
rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
----

. 安装 ELRepo 仓库的 yum 源
+
[source,shell]
----
rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
----

=== 3、查看可用的系统内核包
[source,shell]
----
yum --disablerepo="*" --enablerepo="elrepo-kernel" list available
----

=== 4、安装最新版本内核

[source,shell]
----
yum --enablerepo=elrepo-kernel install kernel-ml
----

include::../../../../../../_components/note.adoc[]

enablerepo 选项开启 CentOS 系统上的指定仓库。默认开启的是 elrepo，这里用 elrepo-kernel 替换。

include::../../../../../../_components/table_footer.adoc[]


=== 5、设置 grub2

. 内核安装好后，需要设置为默认启动选项并重启后才会生效。

. 查看系统上的所有可用内核：
+
[source,shell]
----
sudo awk -F\' '$1=="menuentry " {print i++ " : " $2}' /etc/grub2.cfg
----
+
回显如下：
+
[source,shell]
----
0 : CentOS Linux (4.18.7-1.el7.elrepo.x86_64) 7 (Core)
1 : CentOS Linux (3.10.0-862.11.6.el7.x86_64) 7 (Core)
2 : CentOS Linux (3.10.0-514.el7.x86_64) 7 (Core)
3 : CentOS Linux (0-rescue-063ec330caa04d4baae54c6902c62e54) 7 (Core)
----

. 设置新的内核为 grub2 的默认版本
+
如上所示，服务器上存在 4 个内核，我们要使用 4.18 这个版本，可以通过以下方法来设置：

* 方法1 ：通过如下命令设置
+
[source,shell]
----
grub2-set-default 0
----
+

include::../../../../../../_components/note.adoc[]

其中 0 是上面查询出来的可用内核。

include::../../../../../../_components/table_footer.adoc[]

* 方法2：
+
.. 编辑 `/etc/default/grub` 文件。
+
设置 GRUB_DEFAULT=0，通过上面查询显示的编号为 0 的内核作为默认内核：
+
[source,shell]
----
vim /etc/default/grub

……
GRUB_DEFAULT=0
……
----

.. 生成 grub 配置文件并重启。
+
[source,shell]
----
grub2-mkconfig -o /boot/grub2/grub.cfg

reboot
----

=== 6、重启查看新的内核版本

[source,shell]
----
uname -r
----

=== 7、删除旧内核（可选）

. 查看系统中全部的内核：
+
[source,shell]
----
# rpm -qa | grep kernel

kernel-3.10.0-514.el7.x86_64
kernel-ml-4.18.7-1.el7.elrepo.x86_64
kernel-tools-libs-3.10.0-862.11.6.el7.x86_64
kernel-tools-3.10.0-862.11.6.el7.x86_64
kernel-3.10.0-862.11.6.el7.x86_64
----
. 删除旧内核。

* 方法 1：yum remove 删除旧内核的 RPM 包
+
[source,shell]
----
yum remove kernel-3.10.0-514.el7.x86_64 \
kernel-tools-libs-3.10.0-862.11.6.el7.x86_64 \
kernel-tools-3.10.0-862.11.6.el7.x86_64 \
kernel-3.10.0-862.11.6.el7.x86_64
----

* 方法 2：yum-utils 工具
+
如果安装的内核不多于 3 个，yum-utils 工具不会删除任何一个。只有在安装的内核大于 3 个时，才会自动删除旧内核。

.. 安装yum-utils
+
[source,shell]
----
 yum install yum-utils
----

.. 删除旧版本
+
[source,shell]
----
package-cleanup --oldkernels
----
