---
title: "PUT ObjectLockConfiguration"
description: 本小节主要介绍对象版本锁相关接口。
keywords: 云计算, 山河云, ShanHe, 对象存储, QingStor, WORM, Bucket
collapsible: false
draft: false
weight: 1
---


用于为 Bucket 设置、修改或删除对象版本锁的默认配置。若设置了 Bucket 的对象版本锁的默认配置，则后续上传的对象，均会携带该默认配置。

include::../../../../../../../_components/note.adoc[]

* Bucket 开启对象版本锁的同时会开启多版本功能。
* 该 API 操作的是 Bucket 的对象版本锁的默认配置。生效范围为后续上传的对象。

include::../../../../../../../_components/table_footer.adoc[]


== 请求语法

[source,http]
----
PUT /?object-lock HTTP/1.1
Host: mybucket.jn1.is.shanhe.com
Date: Sun, 16 Aug 2015 09:05:00 GMT
Authorization: authorization string
Content-MD5: string
 
{
    "status": "Enabled"
    "mode": "GOVERNANCE",
    "days": integer,
    "years": integer,
}
----

== 请求参数

无。

== 请求头

此接口仅包含公共请求头。关于公共请求头的更多信息，请参见link:../../../common_header/#_请求头字段_request_header[公共请求头]。

== 请求消息体

调用该 API 需携带如link:#_请求语法[请求语法]中的 Json 消息体。该消息体各字段说明如下。

[cols='1,1,3a,1']
|===
| 名称 | 类型 | 说明 | 是否必须

| status | String | 对象版本锁状态，要求必须是 `Enabled` | 是
| mode | String | 对象版本锁的保护模式。取值为 `GOVERNANCE` 或 `COMPLIANCE`。用户可参考link:../../object_lock/#_概述[前文说明]进行选择。| 是
| days | Integer | 数据保留时间，最大限制为 36500 天。 | 否
| years | Integer | 数据保留时间，最大限制为 100 年。 | 否
|===

include::../../../../../../../_components/note.adoc[]

`days` 与 `years` 只能配置一种，不能同时存在。

include::../../../../../../../_components/table_footer.adoc[]


== 响应头

此接口仅包含公共响应头。关于公共响应头的更多信息，请参见link:../../../common_header/#_响应头字段_response_header[公共响应头]。


== 响应体

无。

== 示例

=== 示例一

仅开启对象版本锁，不配置默认规则。此时，系统会生成一条默认规则。
[source,http]
----
 
{
    mode: GOVERNANCE,
    time: u32,
    hold: bool, 
}
----

* 请求消息
+
[source,http]
----
PUT /?object-lock HTTP/1.1
Host: mybucket.jn1.is.shanhe.com
Date: Sun, 16 Aug 2015 09:05:00 GMT
Authorization: authorization string
Content-MD5: string
 
{
    "status": "Enabled"
}
----

* 响应示例
+
[source,http]
----
HTTP/1.1 200 OK
Server: QingStor
Date: Sun, 16 Aug 2015 09:05:00 GMT
Content-Length: 809
Connection: close
x-qs-request-id: aa08cf7a43f611e5886952542e6ce14b
----

=== 示例二

开启对象版本锁，并设置默认规则或修改默认规则。后续上传的对象，均携带该对象版本锁信息。

* 请求消息
+
[source,http]
----
PUT /?object-lock HTTP/1.1
Host: mybucket.jn1.is.shanhe.com
Date: Sun, 16 Aug 2015 09:05:00 GMT
Authorization: authorization string
Content-MD5: string
 
{
    "status": "Enabled"
    "mode": "GOVERNANCE",
    "days": 1, 
}
----

* 响应示例
+
[source,http]
----
HTTP/1.1 200 OK
Server: QingStor
Date: Sun, 16 Aug 2015 09:05:00 GMT
Content-Length: 809
Connection: close
x-qs-request-id: aa08cf7a43f611e5886952542e6ce14b
----


=== 示例三

删除默认配置规则，但是不能关闭对象版本锁功能。此时，系统会生成一条默认规则。

* 请求消息
+
[source,http]
----
PUT /?object-lock HTTP/1.1
Host: mybucket.jn1.is.shanhe.com
Date: Sun, 16 Aug 2015 09:05:00 GMT
Authorization: authorization string
Content-MD5: string
 
{
    "status": "Enabled"
}
----

* 响应示例
+
[source,http]
----
HTTP/1.1 200 OK
Server: QingStor
Date: Sun, 16 Aug 2015 09:05:00 GMT
Content-Length: 809
Connection: close
x-qs-request-id: aa08cf7a43f611e5886952542e6ce14b
----

