---
title: "术语说明"
description: 本小节主要介绍文件存储 QFS。
draft: false
weight: 2
keywords: 云计算, 文件存储, QFS
---

本文用于解释文件存储 QFS 产品中提及的相关名词，便于用户更好的理解与使用文件存储 QFS。

== 权限组

`权限组` 是用于控制访问文件系统共享路径的权限，不同协议下权限控制的维度不同。

系统默认提供两个权限组：

* `DEFAULT_ACCESS_GROUP_NFS` 是默认的 NFS 协议下的权限组，该权限组不限制任何客户端的访问和权限。
* `DEFAULT_ACCESS_GROUP_SMB` 是默认的 SMB 协议下的权限组，该权限组默认提供 `administrator` 用户进行验证，即使用 SMB 协议进行挂载时需要输入此用户和密码。且 `administrator` 用户具备所有权限。

include::../../../../../_components/note.adoc[]

* 对于没有严格要求访问权限的文件系统，共享时使用对应协议的默认权限组即可。
* 正在使用的权限组不能删除。

include::../../../../../_components/table_footer.adoc[]


== ACL 规则

针对 NFS 权限组的 ACL 规则，有如下说明：

* 每一条 ACL 规则都是对不同 IP 或 IP 段客户端的权限限制。
* 匹配顺序根据 ACL 的优先级进行匹配。ACL 的优先级用数字 1-100 表示，数字越小，匹配优先级越高。
* 初始创建 NFS 权限组时，将默认创建一条 `*、none、不映射、优先级为 100` 的 ACL 规则，其表达的含义是：所有客户端均没有访问权限，此条 ACL 规则优先级最低。
* 相同优先级下，系统会按照 ACL 创建的先后顺序进行匹配，后创建的 ACL 优先。{platform_name_cn}建议不同的 ACL 设置不同的优先级。

ACL 的创建、删除、修改，会影响所有使用该权限组进行共享的文件系统。

=== ACL 的读写权限

ACL 规则的读写权限分为如下三种，用户可根据实际需求进行设置。

* **只读**：授权地址对文件系统有只读权限。
* **读写**：授权地址对文件系统有读写权限。
* **无权限**：对应 None，授权地址对文件系统没有权限。授权地址为 `黑名单`，挂载时也会失败。

=== ACL 的映射关系

ACL 规则的映射关系分为如下三种，用户可根据实际需求进行设置。

* **不映射**：无论客户以何种身份挂载都保留登录身份。
* **所有用户**：无论客户端以什么身份登录都映射为匿名用户。
* **root 用户**：如果客户端以 `root` 身份挂载登录，把 `root` 映射为匿名，如果是普通用户，则保留普通身份登录。