---
title: 什么是 QKE
description: 介绍 QKE 服务功能及版本
keywords: 云计算, QKE, Kubernetes, 容器
weight: 1
linkkey: qke_doc_use_guide,create_hosting_cluste,qke_use_guide,qke_doc_container_faq,qke_doc_question_container_faq
---

//tag::short_intro[]
{k8s_engine_fullname} 是在{platform_name_cn}上构建的企业级分布式多租户的 Kubernetes 容器服务管理平台，集成了{platform_name_cn}的云服务器、存储、网络等资源，可一键部署高可用、高性能的 Kubernetes 集群，支持可视化界面、多集群管理、自动伸缩、运维监控、CI/CD、微服务治理、应用管理、服务与网络管理等业务场景，让您轻松高效地在云端运行 Kubernetes 容器化应用。
//end::short_intro[]

== 为什么选择 {k8s_engine_shortname}

* *按需弹性*：使用{platform_name_cn}资源，结合云平台自动伸缩、按需分配的能力，能够实现根据业务的增减自动分配所需的集群资源。
* *安全稳定*：依托于{platform_name_cn} IaaS 层能力，{k8s_engine_shortname} 集群相较于本地自建集群能提供更好的稳定性，并提供 Master 节点托管等能力。
* *自由选择*：{k8s_engine_shortname} 遵循开源、自由的理念，旨在为用户提供自由的、不受绑定的云原生服务，可对接多种开源在线服务及产品，可管理不同环境、多个厂商的 Kubernetes 集群。
* *简单易用*：{k8s_engine_shortname} 可内置可视化集群管理工具（如 KubeSphere），结合 {k8s_engine_shortname} 控制台界面，提供集群基础资源管理、容器应用管理两大层级的可视化能力。

更多选择理由，请参见link:../function/[产品功能]及link:../advantage/[产品优势]。

== 产品架构

// tag::strcture[]

{k8s_engine_shortname} 整体架构图如下所示。

image::/images/cloud_service/container/qke/qke_structure.svg[]

* {k8s_engine_fullname} 依托于{platform_name_cn} IaaS 层能力，并针对资源调用和管理的对接进行了优化处理。
* {k8s_engine_fullname} 支持原生 Kubernetes 能力，并基于原生 Kubernetes 能力进行了增强和扩展，支持集群管理、资源管理、应用管理等功能的可视化控制。
* 在{k8s_engine_fullname} 基础之上，可扩展安装 KubeSphere、Kubernetes Dashboard 等可视化管理工具，并支持对接{platform_name_cn}服务及第三方开源服务。

//end::strcture[]

// ## 产品形态

// 私有云不支持托管版集群

== 产品定价

{k8s_engine_fullname} 不收取服务费用，用户只需要按实际使用的云资源进行付费。关于收费模式和具体价格，请参见link:../../billing/bill_des/[计费说明]。

== 购买 {k8s_engine_shortname}

登录管理控制台，选择**产品与服务** > *容器服务* > *{k8s_engine_fullname}*，点击**创建集群**进行购买。


