//基本概念解释

== 管理中心

管理中心即主机安全的管理控制中心，部署在独立提供的 Linux 系统主机上，主要功能是把所有客户端信息集中于一体，便于集中监管和配置安全策略，聚合客户端情报信息进行后续的响应以及处置。

== Agent

Agent 是一个独立的本地可执行程序，需要安装在被管控的主机上，以完成管理控制中心下发的任务和策略以及上报主机信息到管理中心。


== 防篡改

防篡改为用户的文件提供保护功能，避免指定目录中的网页、电子文档、图片等类型的文件被黑客、病毒等非法篡改和破坏。

== 防护授权

防护授权是目标主机开启检测防护需要绑定的授权，包括云服务器防护授权和防篡改授权。购买主机安全服务即购买防护授权数量和使用时长。防护授权数量又称防护配额。

例如：

购买了 10 个云服务器防护授权，则可用防护配额数量为 10 个，可分配给 10 台主机分别进行绑定。


== 木马病毒

木马病毒是指隐藏在正常程序中的一段具有特殊功能的恶意代码，是具备破坏和删除文件、发送密码、记录键盘和 DDoS 攻击等特殊功能的后门程序。

== 勒索病毒

勒索病毒是伴随数字货币兴起的一种新型病毒木马，通常以垃圾邮件、服务器入侵、网页挂马、捆绑软件等多种形式进行传播。

一旦遭受勒索病毒攻击，将会使绝大多数的关键文件被加密。被加密的关键文件均无法通过技术手段解密，用户将无法读取原本正常的文件，仅能通过向黑客缴纳高昂的赎金，换取对应的解密私钥才能将被加密的文件无损的还原。黑客通常要求通过数字货币支付赎金，一般无法溯源。

如果关键文件被加密，企业业务将受到严重影响。黑客索要高额赎金，也会带来直接的经济损失，因此，勒索病毒的入侵危害巨大。

== 弱口令/弱密码

弱口令/弱密码是指密码强度低，容易被攻击者破解的密码。

== 漏洞检测

漏洞主要指通用组件而非业务自开发代码产生的漏洞，例如 WordPress 某个 SQL 注入、组件 Bash 的破壳漏洞等。

漏洞检测指基于主机 Agent 在主机内部发现漏洞的一种方式。将漏洞检测模块运行于主机内部，直接进行验证或者采集信息，来判断主机是否存在漏洞。

== 恶意代码

恶意代码又称恶意程序，是指带有攻击或非法远程控制意图的程序，例如：后门、特洛伊木马、蠕虫、病毒等。

恶意程序通过把代码在不被察觉的情况下嵌到另一段程序中，从而达到破坏被感染服务器数据、运行具有入侵性或破坏性的程序等目的。
