//常见问题



//tag::product[]
* <<_什么是主机安全>>
* <<_主机安全单品与安全资源池中的主机安全有何区别>>

== 什么是主机安全？

主机安全是一款针对云主机的安全防护产品，支持主机系统和网络的防护与加固，具备业界领先的勒索病毒专防专杀、东西向流量微隔离、补丁修复、外设管控、文件审计、违规外联检测与阻断等主机安全能力，可全面提升终端安全防护水平，解决主机面临的主要网络安全风险，帮助企业构建主机的安全防护体系。

详细介绍，请参见link:../../intro/intro/[产品介绍]。

== 主机安全单品与安全资源池中的主机安全有何区别？

两者功能一致，但售卖和管理模式有所区别。

主机安全是云平台提供的独立 SaaS 化产品，脱离安全资源池底座进行售卖和使用，价格门槛更低。云平台多租户可共用一个管理中心（一个主机安全实例），管理中心由平台管理员维护，在业务层面数据隔离。

安全资源池中的主机安全是 PaaS 化组件，不能脱离安全资源池底座单独售卖和使用。云平台租户专享一个管理中心（一个主机安全实例），管理中心由租户维护。

//end::product[]


//tag::lincense[]
* <<_能单独购买防篡改授权吗>>
* <<_管理中心剩余授权不足怎么办>>
* <<_如何选择管理中心>>
* <<_为什么管理中心控制台中许可到期日与购买的防护授权到期日不一致>>
* <<_服务过期多久授权会被回收>>

== 能单独购买防篡改授权吗？

不能，防篡改依赖于主机安全许可，必须有主机安全许可（即云服务器防护授权）防篡改才能生效。

== 管理中心剩余授权不足怎么办？

当有多个管理中心时，您可以选择剩余授权数足够的管理中心。若所有管理中心授权都不满足需求，您可以提工单反馈，对管理中心进行扩容。

== 如何选择管理中心？

在当前管理中心授权数足够的情况下，建议您选择同一个管理中心，方便在同一个控制台进行管理操作。因防篡改授权不能单独使用，所以您在购买防篡改授权选择管理中心时，应选择云服务器防护授权所在的管理中心。

== 为什么管理中心控制台中许可到期日与购买的防护授权到期日不一致？

管理中心控制台中的许可是由云平台统一购买的，针对云平台所有租户的全局许可。在主机安全服务控制台购买的授权，为租用许可的有效期，超过有效期后，授权将被回收。您无需关心管理中心控制台中显示的许可信息，只需要关心许可数量是否正确。授权到期日以主机安全服务控制台中显示的到期时间为准。

== 服务过期多久授权会被回收？

服务过期后，您将无法登录管理中心控制台。过期 7 天以内，您可以通过续费恢复服务；过期超过 7 天，防护授权会被回收，管理中心数据会被清理。如果需要继续使用，需要重新购买服务。

//end::lincense[]

//tag::agent[]
* <<_云服务器防护与防篡改共用_agent_吗>>
* <<_linux_系统在线安装_agent_时提示命令不存在>>
* <<_执行在线安装命令时提示网络连接不上>>
* <<_安装_agent_提示安装实体失败系统接受信息失败>>

== 云服务器防护与防篡改共用 Agent 吗？

是的。同一云服务器安装一次 Agent 即可满足所有防护授权的使用。

//tag::agent_install[]

ifdef::discrete[[discrete]]
== Linux 系统在线安装 Agent 时，提示命令不存在

安装 Agent 需要使用到的命令有：cp、rm、tar、id、which、lsmod、insmod、rmmod、grep、head、awk、cat、uname、ls、mkdir、ln、chmod、wget，可自行测试下以上命令是否都已安装，若没有，请手动进行安装。

ifdef::discrete[[discrete]]
== 执行在线安装命令时，提示网络连接不上

在有代理的情况下，请检查在线安装命令中的 IP 是否改为代理 IP，以及检查当前云服务器到代理或管理中心的网络是否通畅，如果不通可能是代理节点端口转发或平台网络出现问题。请提交工单或联系技术支持。

ifdef::discrete[[discrete]]
== 安装 Agent 提示“安装实体失败：系统接受信息失败”

请检查许可是否失效。若已失效，请重新购买服务。
//end::agent_install[]


//end::agent[]