
//包年包月计费模式介绍

包年包月是一种预付费模式，用户根据自身对云资源的使用需求，一次性支付一个月、多个月或多年的费用。购买包年包月资源，可以享受更优惠的价格，适合中长期稳定需求。

云服务器、硬盘、AppCenter 集群均支持包年包月计费模式。

include::../../_components/note.adoc[]
本文仅对计费方式进行说明，具体价格请以产品定价为准。
include::../../_components/table_footer.adoc[]

== 适用场景

包年包月计费方式适合以下业务场景：

* 具有较稳定的业务场景。
* 需要长期使用云资源，追求低成本。

在以上场景中，包年包月计费具备如下优点：

* 单价较按需付费更低，有效期越长，折扣力度越大，可以大幅降低 IT 成本。
* 长期锁定云资源，避免无云资源可用的情况。

== 到期处理

资源到期后，若您未手动续费或自动续费因余额不足而失败，资源将进入保留期，您将不能正常使用云资源，但相关数据会进行保留。

在保留期内，您可以进行续费或充值操作以恢复资源使用。超过保留期，资源将被释放，相关数据将被删除。

include::../../_components/note.adoc[]
* 部分产品会在资源到期后自动转为按需计费模式，此时根据按需计费规则进行扣费处理。
* 不同类型的产品或资源保留期可能不同，请查看对应产品文档。若您不希望资源被暂停服务或删除，请及时续费。
include::../../_components/table_footer.adoc[]

== 退订规则

=== 退款限制

* 退订次数限制
+
个人用户每年享有退订次数配额 2 次，企业用户每年享有退订次数配额 6 次，退订（包含退订续约期订单）次数超出配额上限，则不再支持退订。
+
include::../../_components/attention.adoc[]
* 因用户自身原因，如误操作、合约规划失误等原因退订，默认消耗上述配额。 +
* 因产品功能等问题需要终止并退订包年包月合约，可提工单说明并申请附加配额，不会消耗账户内的默认配额数量。若为恶意退订等情况，平台有权驳回退订需求。
include::../../_components/table_footer.adoc[]

* 退订形式限制
+
以优惠券等形式支付的部分不予退回，未消耗的本金部分会以余额形式退还至用户账号内。
+
在平台活动期购买的包年包月资源，以活动时约定的退订规则为主。

* 退订账户限制
+
可退订配额为主账户/子账户共享配额，请谨慎、合理使用。

=== 退订资金流向

以余额形式退还至用户账户内。

=== 退订费用计算

退订已购买的包年包月资源，将按照以下计算公式算出退订费用，并退还至您的账户内。购买时若使用了优惠券，优惠券不予退还，会在退订费用计算公式中扣除。

*退订费用整体计算公式*：

----
退订费用 = 原支付费用（含折扣） - 优惠券抵扣 - 已消耗的费用
----

* 若退订费用 > 0，退还费用。
* 若退订费用 \<= 0，不予退还。

*已消耗费用的计算公式*：

* 使用期间资源配置未变更
+
----
已消耗的费用 = 原配置的优惠月单价 × 已使用月份 × 折扣系数 + 不足一月的按需计费价格
----
+
include::../../_components/note.adoc[]
已使用月份以及折扣系数基准均按照已使用月份数向下取整。例如已使用 9 个月零 10 天，则已使用月份数为 9，折扣系数为 9 个月所对应的折扣系数。
include::../../_components/table_footer.adoc[]

* 使用期间资源配置变更
+
原包年包月配置A在使用期间因二次操作，如迁移、变更配置等，变为配置B，则计算公式如下：
+
----
已消耗的费用 = 配置A的优惠月单价 × 已使用月份 × 折扣系数 + 配置B月单价 × 已使用月份 + 不足一月的按需计费价格
----
+
include::../../_components/note.adoc[]
已使用月份以及折扣系数基准均按照已使用月份数向下取整。例如已使用 9 个月零 10 天，则已使用月份数为 9，折扣系数为 9 个月所对应的折扣系数。
include::../../_components/table_footer.adoc[]


*费用计算示例*：

假定某配置的云服务器定价信息如下：

* 弹性价格为 0.3元/小时；
* 月单价为 100 元；
* 1 个月折扣率 95%，1 年的折扣率为 80%，2年的折扣率为 70%，3 年的折扣率为 60%。

如下两个场景：

[cols="1,2,5"]
|===
|场景|说明|价格计算

|场景 1
|用户 A 购买时长为 3 年，购买时未使用优惠券，使用 1 年 7 个月 10 天之后进行退订。
a| * 原配置合约价格（含折扣）= 36 &times; 100 &times; 60% = 2160
* 已使用合约价格 = 100 &times;（不含折扣的月单价）&times; 19（月份数）&times; 80%（已使用月份数向下折扣系数）+ 24 &times; 10（不足一个月的小时数）&times; 0.3（按需单价）= 1592
* 退订费用 = 2160（原配置合约价格）- 1592（已使用的合约价格）= 568 > 0

因此，场景 1 下的退款为 568 元。

|场景 2
|用户 B 购买时长为 1 个月，购买时使用了 2 元优惠券，使用 20 天之后进行退订。
a| * 原配置价格（含折扣）= 100 &times; 95% = 95
* 已使用合约价格 = 24&times; 20（不足一个月的按需的小时数）&times; 0.3（按需每小时的单价）= 144
* 退订费用 = 95（含折扣的原配置价格）- 2（优惠券金额）- 144（已使用的合约价格）< 0

因此，场景 2 下的退款为 0。
|===

////
=== 退订流程

. 用户可先在**资源** > **我的配额**的**全局**面查看**合约退订配额**次数是否充足。
. 若配额充足，可自行在需要退订的合约详情页面内，点击**更多操作** > **合约退订**进行退订，并确认可退还金额数。确认无误后，系统将自动返还退订金额。
////


