title: "用户指南"
ignorefiles: [ ".*/_custom"]
# 扩展配置
externalConfigs: docs_center_params.yaml # 相对于当前位置的文件位置，用,作为分隔符的字符串
externalConfigsMap:
  markup.asciidocExt.attributes.platform_name_cn: markup.asciidocExt.attributes.platform_name_cn
  markup.asciidocExt.attributes.brand_name_cap: markup.asciidocExt.attributes.brand_name_cap
  markup.asciidocExt.attributes.brand_name_low: markup.asciidocExt.attributes.brand_name_low
  markup.asciidocExt.attributes.api_url: markup.asciidocExt.attributes.api_url
  markup.asciidocExt.attributes.console_name: markup.asciidocExt.attributes.console_name
  markup.asciidocExt.attributes.qingstor_cap: markup.asciidocExt.attributes.qingstor_cap
  markup.asciidocExt.attributes.qingstor_low: markup.asciidocExt.attributes.qingstor_low
  markup.asciidocExt.attributes.k8s_engine_fullname: markup.asciidocExt.attributes.k8s_engine_fullname
  markup.asciidocExt.attributes.k8s_engine_shortname: markup.asciidocExt.attributes.k8s_engine_shortname
  params.description: params.description
  params.favicon: params.favicon
  params.keywords: params.keywords
  params.logo: params.logo
  params.logoInfo: params.logoInfo
  params.docHostPort: params.docHostPort
  params.disableVersions: params.disableVersions
  params.disablePdf: params.disablePdf
  params.logoLink: params.logoLink

# 扩展样式
externalStyles: theme.json # 相对于当前位置的文件位置，用,作为分隔符的字符串
externalStylesMap:
  $active-color: primary
  $icon-dark-color: primary
  $primary-btn-hover-color: primary-hover
  $active-light-color: secondary
  $icon-light-color: secondary-hover
  $font-title-color: title1
  $menu-switch-active-color: title3
  $banner-description-color: title3
  $font-light-color: help2
  $input-placeholder-color: help2
  $theme-background-color: light-background
  $table-header-background-color: light-background
  $normal-background-color: white-background

markup:
  asciidocExt:
    attributes:
      toc:
      toclevels: 2
      file_output_type: html
      # 全局变量
      platform_name_cn: 云平台
      brand_name_cap:
      brand_name_low: qingcloud
      api_url: https://api.qingcloud.com/iaas/
      console_name: 管理控制台
      # 产品变量
      qingstor_cap: QingStor
      qingstor_low: qingstor
      k8s_engine_fullname: 容器引擎 QKE
      k8s_engine_shortname: QKE


params:
  description: "这里是山河云文档页面"
  favicon: "https://jn1.is.shanhe.com/shanhe/docs/static/images/favicon.ico"
  keywords: "云计算,山河云,shanhe,文档"
  logo: "https://console.shanhe.com/assets/cdn/hinata/6da21fad-b238-421f-a19f-e7efcfcc5569-34783d69-3723-4293-9f44-bc1f0c7d2ac0-shanhe-logo-black.png"
  logoInfo: "山河云"
  logoLink: "/"
  disableVersions: false
  disablePdf: true
  docHostPort: http://enterprise.doccenter.dev.com:8000 # 内嵌版必填
  navLink:
    - title: 控制台
      url: https://console.shanhe.com/

  # PDF 配置
  pdf:
    pdf_projectName: 山河云
    pdf_docVersion: 01
    pdf_copyright: 版权所有 © 北京青云科技股份有限公司
    pdf_legalInfo: 版权所有 © 北京青云科技股份有限公司 2023。保留所有权利。
    pdf_projectVersion: v1.2.2
    pdf_companyFullName: 北京青云科技股份有限公司
    pdf_companyName: 青云
    pdf_companyUrl: https://www.qingcloud.com
    pdf_companyIcon: /images/pdf/qingcloud-logo-icon.png
    pdf_coverDocName: QingCloud 企业云
    pdf_coverDocLogo: /images/pdf/qingcloud-logo-color.png
    pdf_coverDocImage: /images/pdf/cover_doc_image.svg

linkkeyUnchecked:
  # 大数据工作台，仅公有云
  - bigdata_dataomnis_data_summary_manual
  - bigdata_dataomnis_data_development_manual
  - bigdata_dataomnis_databench_faq
  - bigdata_dataomnis_overview_guide
  - bigdata_dataomnis_workspace_guide
  - bigdata_dataomnis_concept_manual
  - bigdata_dataomnis_preparation_manual
  - bigdata_dataomnis_development_process_manual
  - bigdata_dataomnis_restriction_manual
  - bigdata_dataomnis_introduction_manual
  - bigdata_dataomnis_mysql_practice01_manual
  - bigdata_dataomnis_practice02_manual
  - bigdata_dataomnis_video_manual
  - bigdata_dataomnis_overview_news
  - bigdata_dataomnis_price_billing
  # 以下产品，仅公有云
  - bigdata_qingmr_guide
  - bigdata_hbase_guide
  - bigdata_kyligence_guide
  - database_memcached_guide
  - middleware_rocketmq_guide
  - dwh_bi_hashdata_guide
  - bigdata_spark_guide
  - bigdata_queue_manual
  # 老产品
  - bigdata_nifi_guide
  - bigdata_storm_guide
  - middleware_tomcat_guide
  - iot_guide
  - appcenter_image_app_guide
  - container_qke_guide
  #PCDN，已下架，无文档
  - network_pcdn_price_billing
  # 域名与网站，仅公有云
  - domain_dns_function_guide
  - domain_gslb_function_guide
  - domain_ssl_introduction_guide
  - domain_ssl_introduction_share_guide
  - domain_ssl_orders_guide
  - domain_ssl_valid_domain_manual
  - domain_icp_prepare_material_manual
  - domain_icp_prepare_vm_manual
  - icp_site_record
  - icp_site_record_prepare_prepare_vm
  - icp_site_record_manual_change_filing
  - icp_site_record_prepare_prepare_material
  - icp_site_record_faq_basic
  - icp_site_record_faq_icp_faq
  - icp_site_record_policy_site_name
  - icp_site_record_prepare_policy_requirement_policy_requirement
  - icp_site_record_faq_complete
  - icp_site_record_prepare_prepare_material
  - icp_site_record_prepare_pre_approval
  - domain_realname_authen_manual
  - domain_naming_rule_manual
  - domain_dn_record_faq
  - domain_dns_mgtdomainserver_manual
  - domain_dns_resolutionmode_manual
  # sdwan，仅公有云
  - sdwan_gateways_guide
  - sdwan_lines_guide
  - sdwan_gateways_access_manual
  - new_sdwan_nets_guide
  - new_sdwan_operation_log_guide
  - sdwan_guide
  - sdwan_light_box_guide
  - new_sdwan_deploy_script_vcpe_manual
  - sdwan_service_light_box_manual
  - sdwan_physical_cpe_manual
  - new_sdwan_price_new_billing
  - sdwan_new_new_billing_refund
  - sdwan_new_faq_10_faq_sdwan
  - new_sdwan_open_access_point_create_vcpe
  # CDN，仅公有云
  - network_cdn_purges_guide
  - network_cdn_prefetches_guide
  - network_cdn_domains_guide
  - network_cdn_certs_guide
  - network_cdn_guide
  - network_cdn_price_billing
  # 音视频产品，仅公有云
  - rtc_guide
  - rtc_demand_consumption_guide
  - rtc_statistics_guide
  - rtc_application_guide
  - rtc_package_guide
  - rtc_demand_management_guide
  - rtc_demand_task_guide
  - rtc_demand_template_guide
  - rtc_demand_domain_guide
  - rtc_demand_refresh_hot_guide
  - rtc_demand_logs_guide
  - rtc_demand_callback_guide
  - rtc_demand_statistics_guide
  - rtc_demand_resources_guide
  - rtc_intro_manual
  - rtc_novice_demo_manual
  - rtc_sdk_manual
  - rtc_demand_callbac_event_manual
  # QKE，企业云无该链接
  - qke_doc_after_sale_desp_intro
  # 部分安全产品，企业云无
  - security_waf_guide
  - security_waf_parameter_groups_guide
  - security_kms_guide
  - security_high_defense_guide
  - security_ddos_defense_guide
  - security_ddos_defense_price_billing
  - security_ddosip_guide
  - security_ddosip_instance_guide
  - security_ddosip_service_access_guide
  - security_ddosip_domain_defense_guide
  - security_ddosip_monitor_view_guide
  - security_ddosip_course_manual
  - security_ddosip_price_billing
  # Dockerhub & QCI，企业云无
  - containers_docker_repos_guide
  - containers_docker_namespaces_guide
  - containers_docker_users_guide
  - containers_qci_restart_strategy_manual
  # 云市场，企业云无
  - cloudmarket_products_guide
  - cloudmarket_services_guide
  #云桌面，产品及文档已下线
  - compute_cloud_desktop_manual
  # 专属宿主机，已下线，无文档
  - compute_dedicated_host_guide
  - compute_dedicated_host_manual
  #信息已过时，文档没有，也不需要
  - compute_instances_samedata_multiple_faq
  #人工智能产品，已下架
  - ai_deeplearning_guide
  - ai_inference_guide
  # 其他
  - development_docs_api_manual
  - services_contract_manual
  # 对象存储 API，仅公有云有
  - storage_qingstor_api_manual
  - storage_qingstor_acl_api_manual
  - storage_qingstor_cors_api_manual
  - storage_qingstor_bucket_policy_api_manual
  - storage_qingstor_external_mirror_manual
  - storage_qingstor_lifecycle_api_manual
  - storage_qingstor_log_api_manual
  - storage_qingstor_bucket_cross_region_replication_api_manual
  - storage_qingstor_notification_api_manual
  - storage_qingstor_multipart_manual
  - storage_qingstor_multipart_complete_manual
  - storage_qingstor_metadata_manual
  - storage_qingstor_image_process_manual
  - storage_qingstor_price_billing
  - storage_qingstor_news
  - storage_multipart_manual
  #云服务器，仅公有云有
  - compute_instances_news
  - compute_instances_free_after_shutdown_faq
  - compute_instances_ssh_access_faq
  - compute_hpc_price_billing
  # 硬盘，仅公有云
  - storage_disk_news
  - storage_disk_price_billing
  #共享存储，仅公有云
  - storage_vsan_share_creat_manual
  - storage_vsan_share_guide
  #预留合约，企业云已下线对应文档
  - services_reserved_contracts_cancellation_guide





