---
title: "CreateS2SharedTarget"
description: 
draft: false
---
新建共享存储目标，在新建时可以直接添加硬盘作为 backstore，也可以以后添加。

此操作完成后需要调用 link:../update_s2_servers/[UpdateS2Servers] 以应用到共享存储服务器上。

*Request Parameters*

[option="header",cols="1,1,2,1"]
|===
| Parameter name | Type | Description | Required

| s2_server
| String
| 共享存储服务器 ID
| Yes

| export_name
| String
| 共享存储目标名称，或 IQN +
也可以输入短名，QingCloud 会自动帮你补全 IQN。 +
NFS类型，需要以 /mnt/ 开头定义目录名称，SMB 类型，只输入名称，不能包含路径。
| Yes

| target_type
| String
| 共享存储目标类型，类型：ISCSI（vsan），NFS 和 SMB（vnas）
| Yes

| description
| String
| 共享存储目标描述
| No

| volumes.n
| String
| 添加硬盘作为 backstore
| No

| initiator_names.n
| String
| 指定客户端 IQN +
注：仅共享服务类型为 vsan 使用
| No

| s2_group
| String
| 访问共享目录的权限组 ID +
注：仅支持 vnas 服务类型
| No

| zone
| String
| 区域 ID，注意要小写
| Yes
|===

link:../../../parameters/[公共参数]

*Response Elements*

[option="header",cols="1,1,2"]
|===
| Name | Type | Description

| action
| String
| 响应动作

| ret_code
| Integer
| 执行成功与否，0 表示成功，其他值则为错误代码
|===

*Example*

Example Request

----
创建vsan服务类型的共享目录

https://api.shanhe.com/iaas/?action=CreateS2SharedTarget
&s2_server=s2-lxqjtu3l
&export_name=demo
&target_type=ISCSI
&description=demo_descritpion
&zone=jn1a
&COMMON_PARAMS
----

Example Response

----
{
  "action":"CreateS2SharedTargetResponse",
  "s2_shared_target":"s2st-gkps8hq9",
  "ret_code":0
}
----

Example Request

----
创建 vnas 服务类型的共享目录（SMB）

https://api.shanhe.com/iaas/?action=CreateS2SharedTarget
&s2_server=s2-lxqjtu3l
&export_name=smbtest
&target_type=SMB
&s2_group=s2g-1a1212sa
&description=demo_descritpion
&zone=jn1a
&COMMON_PARAMS
----

Example Response

----
{
  "action":"CreateS2SharedTargetResponse",
  "s2_shared_target":"s2st-gkps8hq9",
  "ret_code":0
}
----
